version: '3.4'
services:
  php:
    &php
    container_name: php
    build:
      dockerfile: ./vendor/integrity/tivoli/runtimes/php/Dockerfile
    volumes:
      - ./:/project:rw
  phpdoc:
    &phpdoc
    image: phpdoc/phpdoc:latest
    volumes:
      - ./:/data:rw
  generatephpdoc:
    container_name: generatephpdoc
    <<: *phpdoc
    command: project:run --sourcecode
  unittest:
    <<: *php
    container_name: unittest
    command: "./vendor/bin/phpunit --coverage-text --coverage-html ./build/docs/reports/unit"
  standardscheck:
    <<: *php
    container_name: standardscheck
    command: "./vendor/bin/phpcs --standard=PSR12 ./src -v"
  standardsfix:
    <<: *php
    container_name: standardsfix
    command: "./vendor/bin/phpcbf --standard=PSR12 ./src"
  docs:
    container_name: docs
    build:
      dockerfile: Dockerfile
      context: ./vendor/integrity/tivoli/runtimes/php-apache/
    depends_on:
      - generatephpdoc
      - unittest
    ports:
      - 8088:80
    volumes: 
      - ./build/docs:/var/www/html/docs:rw
    profiles: ["docs"]